routes/web.php
 * Grupo de rutas de acceso exclusivo para el usuario colegio - docentes - materias
 * -----------------------------------------------------------------------
 *
 * @author Xavier Pestana <xpestana4@gmail.com>
 * @license <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
 */
Route::group(['middleware' => ['web', 'auth', 'role:school'], 'prefix' => 'colegio'], function () {
    Route::get('show/teachers', 'TeacherController@table')->name('teachers.table');
    Route::post('edit/teachers/psw', 'TeacherController@psw')->name('teachers.psw');
    Route::resource(
        'teachers',
        'TeacherController',
        ['names' =>
        ['index' => 'teachers.index']],
        ['except' => ['create','store','edit','update','show','destroy']]
    );
    Route::get('show/courses', 'CourseController@table')->name('courses.table');
    Route::get('show/sections', 'CourseController@sections')->name('courses.sections');
    Route::resource(
        'courses',
        'CourseController',
        ['names' =>
        ['index' => 'courses.index']],
        ['except' => ['create','store','edit','update','show','destroy']]
    );
});

/**
 * -----------------------------------------------------------------------
 * Grupo de rutas de acceso exclusivo para el usuario docente
 * -----------------------------------------------------------------------
 *
 * @author Xavier Pestana <xpestana4@gmail.com>
 * @license <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
 */


Route::group(['middleware' => ['web', 'auth', 'role:teacher|student'], 'prefix' => 'docente'], function () {
    Route::get('profile', 'TaskController@profile')->name('materias.profile');
    Route::post('save', 'TaskController@save')->name('tasks.save');
    Route::get('showcomment', 'TaskController@showcomment')->name('showcomment');
    Route::delete('delete_comment', 'TaskController@delete_comment')->name('delete.comment');
    Route::post('comment', 'TaskController@comment')->name('comment');
    Route::post('image/avatar', 'TeacherController@avatar');
    Route::post('update', 'TeacherController@profile')->name('profile');
    Route::get('students/{id}', 'TaskController@students')->name('tasks.students');
    Route::get('messages/{id}', 'TaskController@messages')->name('tasks.messages');
    Route::get('showresponse', 'TaskController@showresponse')->name('showresponse');
    Route::get('destroy', 'StudentActivitiesController@destroy')->name('studentActivity.delete');
    Route::resource(
        'tasks',
        'TaskController',
        ['names' =>  ['index' => 'tasks.index']],
        ['except' => ['create','store','edit','update','show','destroy']]
    );
    Route::get('search', 'ChatController@search')->name('chat.search');
    Route::get('show/students', 'ChatController@students')->name('chat.students');
    Route::get('show/side', 'ChatController@sidebar_message')->name('chat.sidebar');
    Route::get('show/count', 'ChatController@count_message')->name('chat.count');
    Route::resource(
        'chat',
        'ChatController',
        ['names' =>  ['index' => 'chat.index']],
        ['except' => ['create','store','edit','update','show','destroy']]
    );
});
Route::group(['middleware' => ['web', 'auth', 'role:teacher'], 'prefix' => 'docente'], function () {

    Route::resource(
        'evaluations',
        'evaluationController',
        ['names' =>  ['index' => 'evaluations.index']],
        ['except' => ['create','store','edit','update','show','destroy']]
    );
    Route::resource(
        'evaluationPlan',
        'evaluationPlanController',
        ['names' =>  ['index' => 'evaluationPlan.index']],
        ['except' => ['create','store','edit','update','show','destroy']]
    );
    Route::resource(
        'evaluacion',
        'evPrimaryController',
        ['names' =>  ['index' => 'evaluacion.index']],
        ['except' => ['create','store','edit','update','show','destroy']]
    );
    Route::resource(
        'evaluacionPlan',
        'evPLanPrimaryController',
        ['names' =>  ['index' => 'evaluacionPlan.index']],
        ['except' => ['create','store','edit','update','show','destroy']]
    );
    });
/**
 * -----------------------------------------------------------------------
 * Grupo de rutas de acceso exclusivo para el usuario estudiante
 * -----------------------------------------------------------------------
 *
 * @author Xavier Pestana <xpestana4@gmail.com>
 * @license <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
 */


Route::group(['middleware' => ['web', 'auth', 'role:student'], 'prefix' => 'activities'], function () {

   Route::get('response', 'StudentActivitiesController@response')->name('studentActivity.response');
    Route::get('published', 'StudentActivitiesController@published')->name('studentActivity.published');
   Route::get('task', 'StudentActivitiesController@activities')->name('studentActivity.activities');

   Route::resource(
        'student',
        'StudentActivitiesController',
        ['names' =>  [
            'index' => 'studentActivity.index',
            'show' => 'studentActivity.show',
        ]],
        ['except' => ['create','store','edit','update','show','destroy']]
    );

});
/**
 * -----------------------------------------------------------------------
 * Grupo de rutas de acceso exclusivo para el desarrollo de APISRESTfull
 * -----------------------------------------------------------------------
 *
 * @author Xavier Pestana <xpestana4@gmail.com>
 * @license <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
 */

Route::get('get/families/{school}', 'ApiController@families');
Route::get('get/representatives/{school}', 'ApiController@representatives');
Route::get('get/students/{school}', 'ApiController@students');
Route::get('get/sesion/{school}/{document}', 'ApiController@sesion');



/**
 * -----------------------------------------------------------------------
 * Grupo de rutas de acceso para el usuario escolar
 * -----------------------------------------------------------------------
 *
 * @author William Páez <paez.william8@gmail.com>
 * @license <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
 */
Route::group(['middleware' => ['web', 'auth', 'role:school'], 'prefix' => 'pagos'], function () {
       
    Route::post('settings/iva', 'PaymentSettingController@iva')->name('payment-settings.iva');
    Route::post('settings/headers', 'PaymentSettingController@headers')->name('payment-settings.headers');
    Route::post('settings/simple', 'PaymentSettingController@simple')->name('payment-settings.simple');
    
    Route::resource(
        'configuraciones',
        'PaymentSettingController',
        [
            'names' => ['index' => 'payment-settings.index'],
            'except' => ['create','store','edit','update','show','destroy'],
        ],
    );

    Route::resource(
        'conceptos',
        'ConceptController',
        [
            'names' => [
                'index' => 'concepts.index',
                'create' => 'concepts.create',
                'store' => 'concepts.store',
                'show' => 'concepts.show',
                'edit' => 'concepts.edit',
                'update' => 'concepts.update',
                'destroy' => 'concepts.destroy'
            ],
            
        ],
    );

    Route::post('cookies', 'CookieController@save')->name('coin.save');
    Route::resource(
        'planes',
        'PlanController',
        [
            'names' => [
                'index' => 'plans.index',
                'create' => 'plans.create',
                'store' => 'plans.store',
                'show' => 'plans.show',
                'edit' => 'plans.edit',
                'update' => 'plans.update',
                'destroy' => 'plans.destroy'
            ],
        ],
    );


    Route::resource(
        'installments',
        'InstallmentController',
        [
            'names' => [
                'index' => 'installments.index',
                'create' => 'installments.create',
                'store' => 'installments.store',
                'show' => 'installments.show',
                'edit' => 'installments.edit',
                'update' => 'installments.update',
                'destroy' => 'installments.destroy'
            ],
        ],
    );

    Route::resource(
        'inscripciones',
        'EnrollmentController',
        [
            'names' => [
                'index' => 'enrollments.index',
                'create' => 'enrollments.create',
                'store' => 'enrollments.store',
                'show' => 'enrollments.show',
                'edit' => 'enrollments.edit',
                'update' => 'enrollments.update',
                'destroy' => 'enrollments.destroy'
            ],
        ],
    );
    Route::get('inscripciones/show/vue-list', 'EnrollmentController@vueList')->name('enrollments.vue-list');
    Route::get('list-enrollments', 'EnrollmentController@listEnrollments')->name('enrollments.list-enrollments');

Route::get('list/installments', 'PaymentController@installments')->name('payments.installments');
Route::get('student', 'PaymentController@liststudents')->name('payments.list_students');

    Route::resource(
        'facturar',
        'PaymentController',
        [
            'names' => [
                'index' => 'payments.index',
                'create' => 'payments.create',
                'store' => 'payments.store',
                'show' => 'payments.show',
                'edit' => 'payments.edit',
                'update' => 'payments.update',
                'destroy' => 'payments.destroy'
            ],
        ],
    );
    Route::get('show/vue-list', 'PaymentController@vueList')->name('payments.vue-list');

app/evaluation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class evaluation extends Model
{
    protected $fillable = ['user_id', 'evaluation_plan_id', 'description'];

    public function evaluationPlan()
    {
        return $this->belongsTo(evaluationPlan::class);
    }
}

app/Http/Controllers/evaluationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Season;
use App\Course;
use App\Period;
use App\User;
use App\evaluation;
use App\teacherNotify;
use App\evaluationPlan;

class evaluationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $course_id = $request->course_id;
        $season = Season::where('status','1')
                        ->where('school_id',auth()->user()->profile->teacher->school_id)
                        ->first();
        $period = Period::where('season_id',$season->id)
                        ->where('status',1)
                        ->first();
       $students = DB::table('users')
            ->join('profiles', 'users.id', '=', 'profiles.user_id')
            ->join('students', 'profiles.id', '=', 'students.profile_id')
            ->join('enrollments', 'students.id', '=', 'enrollments.student_id')
            ->select('users.*','profiles.*')
            ->where('enrollments.section_id',$request->section_id)
            ->orderBy('profiles.last_name_1', 'asc')
            ->get();

            $plan = evaluationPlan::where('period_id',$period->id)
                                    ->where('section_id', $request->section_id)
                                    ->get();
                                    
        return view('evaluations.secundary.index', compact('students','plan','course_id'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $course = Course::find($request->course_id);

        $season = Season::where('status','1')
                        ->where('school_id',auth()->user()->profile->teacher->school_id)
                        ->first();
        $period = Period::where('season_id',$season->id)
                        ->where('status',1)
                        ->first();
        
        $student = User::find($request->user_id);
        
        $plan = evaluationPlan::where('period_id',$period->id)
                                    ->where('section_id', $course->courses_sections_user->last()->section->id)
                                    ->get();
        //dd($plan);
        return view('evaluations.secundary.modal', compact('student','plan','course'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        $course = Course::find($id);

        $season = Season::where('status','1')
                        ->where('school_id',auth()->user()->profile->teacher->school_id)
                        ->first();
        $period = Period::where('season_id',$season->id)
                        ->where('status',1)
                        ->first();
        
        if ($course->grade->level->id =='5' || $course->grade->level->id =='6' ||  $course->grade->level->id =='7') {
            
            if (!is_null($period)) {
                $plan = evaluationPlan::where('period_id',$period->id)
                                    ->where('section_id', $course->courses_sections_user->last()->section->id)
                                    ->get();
                return view('evaluations.index', compact('course', 'season', 'period','plan'));
            } else {
               return 'Periodo no activo, vuelve atras y comuniquese con el colegio';
            }
        }else{
            if (!is_null($period)) {
                $plan = evaluationPlan::where('period_id',$period->id)
                                    ->where('section_id', $course->courses_sections_user->last()->section->id)
                                    ->get();
                return view('evaluations.primary', compact('course', 'season', 'period','plan'));
            } else {
               return 'Periodo no activo, vuelve atras y comuniquese con el colegio';
            }
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       
        $final = $i = 0;
         $count = count($request->nota);
         
        foreach ($request->nota as $nota) {
            evaluation::where('evaluation_plan_id', $request->plan_id[$i])->where('user_id', $request->user_id)->delete();

            $evaluation = new evaluation;
            $evaluation->user_id = $request->user_id;
            $evaluation->evaluation_plan_id = $request->plan_id[$i];
            $evaluation->description = $nota;
            $evaluation->save();
            $i++;
        }
        return 0;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/evaluations/primary/index.blade.php
<style>
    .table td, .table th {
    padding: 0.25rem;
}
</style>

<div style="overflow-x: scroll" class="table-responsive">
                                    <table class="table full-color-table full-muted-table hover-table">
                                        <tbody>
                                            @foreach($students as $student)
                                            <tr>
                                                <td style="font-size: 13px">{{ $student->last_name_1 }} {{ $student->last_name_2 }} {{ $student->first_name_1 }} {{ $student->first_name_2 }}</td> 
                                                <td><button type="button" class="btn btn-success" title="Agregar Nota" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap" onclick="notas('{{ $student->user_id }}','{{ $course_id }}')"><i class="fa fa-plus"></i> Agregar Evaluación</button></td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>

resources/views/evaluations/primary/modal.blade.php
           @if(!$plan->isEmpty())
           @php
           $i=0;
           @endphp
            <form id="form_ev" accept-charset="utf-8">
                @csrf
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel1">Alumno: {{ $student->profile->last_name_2 }} {{ $student->profile->last_name_1 }} {{ $student->profile->first_name_2 }} {{ $student->profile->first_name_1 }}</h4>

                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <div class="row">
                @foreach($plan as $activity)
                @php
                    $ev = App\evaluation::where('user_id',$student->profile->user_id)->where('evaluation_plan_id',$activity->id)->first();
                    
                    if(!is_null($ev)){
                        $eval = $ev->description;
                    }else{
                        $eval = null;
                    }
                    @endphp
                    <div class="col-md-12">
                        <div id="accordian-3">
                            <div class="card m-b-0">
                                <a class="card-header text-decoration-none" id="heading11">
                                    <button type="button" class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse{{ $i }}" aria-expanded="false" aria-controls="collapse{{ $i }}">
                                    <h5 class="m-b-0">{{ $activity->description }}</h5>
                                    </button>
                                </a>
                                <div id="collapse{{ $i }}" class="collapse" aria-labelledby="heading11" data-parent="#accordian-3" style="">
                                    <div class="card-body">
                                        <textarea name="nota[]" class="form-control" rows="5" placeholder="Evaluacion del Alumno (1000 palabras)" maxlength="1000">{{ $eval }}</textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    @php
                    $i++;
                    @endphp
                    <input type="hidden" id="plan_id" name="plan_id[]" value="{{ $activity->id }}" >
                @endforeach
                
                <input type="hidden" id="user_id" name="user_id" value="{{ $student->profile->user_id }}" >
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                <button id="save" type="submit" class="btn btn-primary">Guardar</button>
            </div>
            </form>

            <script>
                /*******  Guardar nota  ********/
$( "#form_ev" ).submit(function(e) {
e.preventDefault();
var plan = $("#plan_id").val();
  $(".save").prop('disabled', true);
  datos = $("#form_ev").serialize();
          
$.ajax({
        type:'PUT',
        data:datos,
        url:"{{ url('docente/evaluacion/') }}/" + plan,
        })
        .done(function(response) {
            $(".save").prop('disabled', false);
            Swal.fire({
                position: 'center-center',
                icon: 'success',
                title: 'Guardado exitosamente',
                showConfirmButton: false,
                timer: 1500
            }) 
            $.ajax({
         type : "GET",
         data : {"section_id" : {{ $course->courses_sections_user->last()->section->id }}, "_token": "{{ csrf_token() }}", "course_id": {{ $course->id }} },
         url : "{{ route('evaluacion.create') }}",
         success : function(data){
            $('#student').html(data);
         }
            });
            $('#exampleModal').modal('hide');
        })
        .fail(function(response) {
            $(".save").prop('disabled', false);
            Swal.fire({
                icon: 'error',
                title: 'Oops...',
                text: 'Error, intente denuevo.',
                })
        }) 
});
            </script>
            @else
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel1">Debe Agregar plan de Evaluación</h4>

                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
            @endif

resources/views/evaluations/primary/plan.blade.php
                                @if(!$plan->isEmpty())
                                @foreach($plan as $activity)
                                    <div class="row">
                                    
                                    <div class="col-md-12 nopadding">
                                        <div class="form-group">
                                        <label for="description">Descripcion</label>
                                            <input type="text" class="form-control" id="description" value="{{ $activity->description }}" name="descriptions[]" value="" placeholder="Descripcion" required="" disabled="">
                                        
                                        </div>
                                    </div>
                                    <div class="col-md-8 nopadding">
                                        <div class="form-group">
                                            <label for="date">Fecha</label>
                                            <input type="date" class="form-control" id="date" name="dates[]" placeholder="Fecha" value="{{ $activity->fecha }}" required="" disabled="">
                                        </div>
                                    </div>
                                    
                                    <div class="col-sm-3 nopadding"> 
                                        <div class="form-group"> 
                                            <div class="input-group"> 
                                                <div class="input-group-append"> 
                                                    <button class="btn btn-danger mt-4" type="button" onclick="remove_education_fields('{{ $activity->id }}')"><i class="fa fa-minus"></i></button> 
                                                </div> 
                                            </div> 
                                        </div> 
                                    </div>
                                    
                                    </div>
                                    @endforeach
                                    @endif